"""add endpoint_map to projects

Revision ID: 3b2c2b1b7ae2
Revises: c5bcd23de1e5
Create Date: 2026-07-08 10:45:14.159712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3b2c2b1b7ae2'
down_revision: Union[str, None] = 'c5bcd23de1e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('endpoint_map', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('projects', sa.Column('endpoint_map_updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True))
    op.drop_index('idx_projects_created_at', table_name='projects')
    op.create_index('idx_projects_created_at', 'projects', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_projects_created_at', table_name='projects')
    op.create_index('idx_projects_created_at', 'projects', [sa.text('created_at DESC')], unique=False)
    op.drop_column('projects', 'endpoint_map_updated_at')
    op.drop_column('projects', 'endpoint_map')
    # ### end Alembic commands ###
