"""add generation status tracking to tickets

Revision ID: a72beb683704
Revises: 3b2c2b1b7ae2
Create Date: 2026-08-03 17:57:31.514980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a72beb683704'
down_revision: Union[str, None] = '3b2c2b1b7ae2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('generation_status', sa.String(length=20), nullable=False, server_default='not_started'))    
    op.add_column('tickets', sa.Column('generation_error', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'generation_error')
    op.drop_column('tickets', 'generation_status')
    # ### end Alembic commands ###
