"""create initial tables

Revision ID: c5bcd23de1e5
Revises: 
Create Date: 2026-07-05 14:44:01.442666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c5bcd23de1e5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('framework', sa.String(length=50), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint("framework IN ('laravel','fastapi','spring_boot')", name='ck_projects_framework'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_projects_created_at', 'projects', [sa.text('created_at DESC')], unique=False)
    op.create_index('idx_projects_framework', 'projects', ['framework'], unique=False)
    op.create_table('tickets',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('acceptance_criteria', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_cases',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('input_payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('headers_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('expected_status_code', sa.Integer(), nullable=False),
    sa.Column('expected_response_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('assertion_notes', sa.Text(), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint("type IN ('happy_path','negative','validation','security','edge_case')", name='ck_test_cases_type'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_test_cases_approved', 'test_cases', ['approved'], unique=False)
    op.create_index('idx_test_cases_ticket_id', 'test_cases', ['ticket_id'], unique=False)
    op.create_index('idx_test_cases_type', 'test_cases', ['type'], unique=False)
    op.create_table('test_runs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('newman_output_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('total_tests', sa.Integer(), nullable=False),
    sa.Column('passed', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('skipped', sa.Integer(), nullable=False),
    sa.Column('avg_response_time_ms', sa.Float(), nullable=False),
    sa.Column('collection_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('executed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending','running','completed','failed')", name='ck_test_runs_status'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_test_runs_status', 'test_runs', ['status'], unique=False)
    op.create_index('idx_test_runs_ticket_id', 'test_runs', ['ticket_id'], unique=False)
    op.create_table('bug_reports',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('test_case_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('steps_to_reproduce', sa.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('expected_result', sa.Text(), nullable=False),
    sa.Column('actual_result', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint("severity IN ('critical','high','medium','low')", name='ck_bug_reports_severity'),
    sa.ForeignKeyConstraint(['run_id'], ['test_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_bug_reports_run_id', 'bug_reports', ['run_id'], unique=False)
    op.create_index('idx_bug_reports_severity', 'bug_reports', ['severity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_bug_reports_severity', table_name='bug_reports')
    op.drop_index('idx_bug_reports_run_id', table_name='bug_reports')
    op.drop_table('bug_reports')
    op.drop_index('idx_test_runs_ticket_id', table_name='test_runs')
    op.drop_index('idx_test_runs_status', table_name='test_runs')
    op.drop_table('test_runs')
    op.drop_index('idx_test_cases_type', table_name='test_cases')
    op.drop_index('idx_test_cases_ticket_id', table_name='test_cases')
    op.drop_index('idx_test_cases_approved', table_name='test_cases')
    op.drop_table('test_cases')
    op.drop_table('tickets')
    op.drop_index('idx_projects_framework', table_name='projects')
    op.drop_index('idx_projects_created_at', table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
